teams: # []
  - id: mindfield
    name: The MindField
    score: 0
  - id: fitten
    name: Fitten Foundation
    score: 0
  - id: ques
    name: Theta Alpha
    score: 0
  - id: rhos
    name: Alpha Omicron Sigma
    score: 0
